### ISSUE TITLE
Provide options to customize keys separator

### ISSUE THREAD

**Issue by parro-it** [watson/flatten-obj#1]
Hi, I need to add an option to customize the character used to separate object keys when they are joined.
I could provide a PR to implement this use case, I think I'll add an option argument to returned function.
I make it defaults to `.`  to keep compatibility with previous version.

Any think or suggestion?

**Comment by watson** [comment]
I think it makes sense. But I think we need to break the current API to better support this.

Currently the main function exposed by the module takes a list of classes that should be blacklisted - one per function argument. This needs to be changed since we can't tell the difference between a random class and an options object:

``` js
// default options (like today)
var flatten = require('flatten-obj')()

// use custom separator
var flatten = require('flatten-obj')({ separator: '/' })

// use blacklist
var flatten = require('flatten-obj')([KlassA, KlassB])

// use custom separator + blacklist
var flatten = require('flatten-obj')({ separator: '/', blacklist: [KlassA, KlassB] })
```

This also allows me to get rid of `Array.prototype.slice.call(arguments)` which is de-opting the function :disappointed: 

You are welcome to make a PR, or just say the word and I'll update this if you'd like :smiley:

**Comment by parro-it** [comment]
If we're going to change the api, I think it could be better to add the option object directly to the function call:

``` js
var Klass = function () {
  this.baz = 1;
};

var flatten = require('flatten-obj');

var obj = {
  foo: {
    bar: new Klass()
  }
};

// outputs `{ 'foo_bar': { baz: 1 } }`
console.log(flatten(obj, {
    separator: '/', 
    blacklist: [Klass]
}));
```

or, if I'm fine using `_` and no class exclusion, 

``` js
console.log(flatten(obj));
```

Seem simpler to me... what do you think?
I will write a PR with pleasure :smile:

**Comment by watson** [comment]
FYI: I just realized that I wrote `whitelist` in my comment above - should have been `blacklist` of cause. I updated the comment accordingly

**Comment by parro-it** [comment]
Me too :smile:

**Comment by watson** [comment]
Back to your question.... hmmm...

The reason why I originally initialised the function with some options was because of my use-case. I use this module to flatten MongoDB objects and I have a `db` variable which holds the connection to my database that I share and use across my app.

Here's an example of what my `lib/db.js` file look like. I then require this file from where I need to access the database and have easy access to the `db.flatten` function:

``` js
var mongojs = require('mongojs')
var Flatten = require('flatten-obj')

var db = mongojs(conf.mongoUri, ['users', 'teams'])

db.flatten = Flatten(
  mongojs.ObjectId,
  mongojs.DBRef,
  mongojs.Timestamp,
  mongojs.MinKey,
  mongojs.MaxKey,
  mongojs.NumberLong
)

module.exports = db
```

That being said, I could easily rewrite it to support the runtime approach:

``` js
var opts = { blacklist: [
  mongojs.ObjectId,
  mongojs.DBRef,
  mongojs.Timestamp,
  mongojs.MinKey,
  mongojs.MaxKey,
  mongojs.NumberLong
]}

db.flatten = function (obj) {
  return flatten(obj, opts)
}
```

What's your thoughts/use-case for making this change? - love to hear it :smiley:

**Comment by watson** [comment]
hmm... you know what? Let's go with your approach. It's more simple - I like simple

**Comment by parro-it** [comment]
I'm writing a tools to run npm scripts in a better way.
So I need to inject `package.json` content into ENV vars, like npm do.

I have e.g. to transform: 

``` js
{
 name: 'my-pkg',
 dependecies: {
   "mydep": "*",
   "otherDep": "*"
 }
}
```

to

``` js
{
 name: 'my-pkg',
 dependecies_mydep: "*",
 dependecies_otherDep: "*"
}
```

And then I inject that into scripts env.
I'm actually using [this module I pick somewhere on GH](https://github.com/parro-it/runscripts/blob/master/modules/flatten-obj.js) but that's weird...

While refactoring it and try to extract to it's own module, I choose to call it `flatten-obj`
and discover your module...

**Comment by watson** [comment]
Looking forward to the PR :smiley:

**Comment by parro-it** [comment]
Done!

**Comment by parro-it** [comment]
Some other things that I think could be improved:
- Travis is testing on old node version only, I would includes also 0.12, 4, 5
- There is no lint configured, I saw you use standard in your latest module, it's ok if I introduce that?
- I introduced a .editorconfig to simplifiy my life while editing, but I've not pushed it. Ok to add it?

**Comment by watson** [comment]
@parro-it yeah, I totally agree about the linting and travis tests. I haven't been modifying this module for a while, so it's using my old style of coding as well. I was gonna add the standard linter after I'd merged the PR, but didn't want to bother you with it now - I also saw a few things that I wanted to improve code-wise as well.

I think it's easier to digest this PR if we don't add the linter just yet and do it in a separate PR - or maybe I just do it and clean up some of the other stuff I saw - else every line of code will change and the diff will be impossible to read :wink: 

And yes, please keep the editor config outside the repo :smiley: 

This is the travis file I usually use now: https://github.com/watson/module-details-from-path/blob/master/.travis.yml

**Comment by parro-it** [comment]
:+1: @watson that's fair. Regarding the .travis file you linked, there is a reason you don't use `sudo: false` to leverage [Travis container based infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure/)?

**Comment by watson** [comment]
@parro-it because https://twitter.com/wa7son/status/652844538608898049

**Comment by parro-it** [comment]
Ah, you're right, I kept using it, but I'll remove from my new repos, thank you!

**Comment by watson** [comment]
@parro-it Just merged your PR - thanks a lot :smiley:
I'll go ahead and add standard now :smiley:

**Comment by parro-it** [comment]
Awesome! I look forward to a new release on npm and then start using this as a dep.

**Comment by watson** [comment]
@parro-it Ups, I missed an important point when we were talking about dropping the main generator function. The `isBlacklisted` function was previously only created once when calling the generator and just reused every time I called the generated flatten function.

Now it's created every time an object needs to be flattened, so I think V8 can't optimise it in the same way (in my use-case).

I think I'll make it into a generator function again - sorry about not thinking about this before.

If you just need this for a one-off flattening, you can just chain the function calls:

``` js
var Flatten = require('flatten-obj')

flatten({ separator: '_' })(obj)
```

**Comment by watson** [comment]
@parro-it actually, if I refactor the code a little bit I can reuse the `iterator` function as well - that way no function have to be created when calling the `flatten` function :smiley:

**Comment by parro-it** [comment]
No worries! Another option is to add a `blacklist` argument to it. Then you can move outside the main function and pass the blacklist arg...

**Comment by parro-it** [comment]
Oh, I guess you could pass `blacklist` and `separator` as arguments...
Are you sure there are noticeable performance gain? `isBlacklisted` create a new function anyway each time it's called (the `some` arg)

**Comment by watson** [comment]
@parro-it it's now realised on npm as v3.0.0 - I managed to ensure no closures are generated when running the hotter `flatten` function. They are now only created when calling the generator function.

**Comment by parro-it** [comment]
I see, looks good, thank you! I'll start to use it

**Comment by parro-it** [comment]
Also, I add it to my [awesome-microlibs list](https://github.com/parro-it/awesome-microlibs) :smiley_cat:

**Comment by watson** [comment]
@parro-it thanks :) Stared it!

**Comment by parro-it** [comment]
Thank you so much!
